services:
  db:
    image: postgres:16-alpine
    container_name: portfolio-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: portfolio_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  # 可选：数据库图形化管理界面，方便你直接在浏览器查看数据
  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "58080:80"
    depends_on:
      - db